[[git_workspace]]
name = "prelude"
url = "https://github.com/trunk-io/prelude.git"
reference = "v0.0.12"

[options.prelude.runtime]
node.version = "22.12.0"
python.version = "3.13.0"
go.version = "1.23.4"

[options.prelude.tool]
actionlint.check = true
actionlint.version = "1.7.7"
shfmt.version = "3.4.2"
shfmt.fmt = true
shellcheck.check = true
shellcheck.version = "0.10.0"
do_not_land.check = true

[[ignore]]
globs = [".tk/baseline/**"]
